
import { GoogleGenAI, Chat } from "@google/genai";
import { AiAction, Tone } from '../types';

// Per guidelines, API key must be from process.env.API_KEY
const apiKey = process.env.API_KEY;
if (!apiKey) {
    console.warn("API_KEY environment variable not set. AI features will not work.");
}
// FIX: Initialize GoogleGenAI with named apiKey parameter as per guidelines.
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

// FIX: Select model based on task type, 'gemini-2.5-flash' is suitable for basic text tasks.
const flash = 'gemini-2.5-flash';

const getPrompt = (action: AiAction, text: string, options?: { tone?: Tone; prompt?: string }): string => {
    switch (action) {
        case AiAction.IMPROVE:
            return `Improve the following text for clarity, grammar, and style. Only return the improved text, without any additional commentary:\n\n---\n${text}\n---`;
        case AiAction.SUMMARIZE_SELECTION:
            return `Summarize the following text concisely:\n\n---\n${text}\n---`;
        case AiAction.CHANGE_TONE:
            return `Rewrite the following text in a ${options?.tone || Tone.PROFESSIONAL} tone. Only return the rewritten text, without any additional commentary:\n\n---\n${text}\n---`;
        case AiAction.SUMMARIZE_DOCUMENT:
            return `Provide a concise summary of the following document:\n\n---\n${text}\n---`;
        case AiAction.GENERATE_OUTLINE:
            return `Generate a markdown-formatted outline for a document with the following content:\n\n---\n${text}\n---`;
        case AiAction.SUGGEST_TITLES:
            return `Suggest 5 potential titles for the following document. Provide them as a markdown-formatted list, without any introductory text:\n\n---\n${text}\n---`;
        case AiAction.GENERATE_OUTLINE_FROM_PROMPT:
            return `Generate a detailed, markdown-formatted document outline based on the following prompt:\n\n---\n${options?.prompt}\n---`;
        default:
            throw new Error(`Unknown AI action: ${action}`);
    }
};

export const runAiAction = async (
    action: AiAction,
    text: string,
    options?: { tone?: Tone; prompt?:string }
): Promise<string> => {
    if (!apiKey) {
        return "Error: API_KEY is not configured. Please set the API_KEY environment variable.";
    }
    try {
        const prompt = getPrompt(action, text, options);
        
        const response = await ai.models.generateContent({
            model: flash,
            contents: prompt,
        });

        const resultText = response.text;
        
        if (!resultText) {
            throw new Error("No text generated by AI.");
        }
        
        return resultText.trim();
    } catch (error) {
        console.error("Error calling Gemini API:", error);
        if (error instanceof Error) {
            return `Error: ${error.message}`;
        }
        return "An unknown error occurred while contacting the AI service.";
    }
};

// --- New AI Features ---

// Chatbot
let chat: Chat | null = null;
const getChat = () => {
    if (!chat) {
        chat = ai.chats.create({
            model: flash,
        });
    }
    return chat;
};

export const sendMessageToChat = async (message: string) => {
    if (!apiKey) throw new Error("API Key not configured");
    const chatInstance = getChat();
    const response = await chatInstance.sendMessage({ message });
    return response.text;
};

// Image Generation
export const generateImage = async (prompt: string, aspectRatio: string) => {
    if (!apiKey) throw new Error("API Key not configured");
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/png',
          aspectRatio,
        },
    });
    const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
    return `data:image/png;base64,${base64ImageBytes}`;
}

// Video Generation
export const generateVideo = async (prompt: string, imageBase64: string, aspectRatio: '16:9' | '9:16', onProgress: (message: string) => void) => {
    if (!apiKey) throw new Error("API Key not configured");
    onProgress('Starting video generation...');
    let operation = await ai.models.generateVideos({
        model: 'veo-3.1-fast-generate-preview',
        prompt,
        image: {
            imageBytes: imageBase64,
            mimeType: 'image/png',
        },
        config: {
            numberOfVideos: 1,
            resolution: '720p',
            aspectRatio: aspectRatio,
        }
    });

    onProgress('Processing video... this can take a few minutes.');
    while (!operation.done) {
        await new Promise(resolve => setTimeout(resolve, 10000));
        onProgress('Checking video status...');
        operation = await ai.operations.getVideosOperation({ operation: operation });
    }

    onProgress('Video generated successfully!');
    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (!downloadLink) {
        throw new Error('Video generation finished but no download link was found.');
    }
    
    onProgress('Downloading video data...');
    // The response.body contains the MP4 bytes. You must append an API key when fetching from the download link.
    const response = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
    const videoBlob = await response.blob();
    return URL.createObjectURL(videoBlob);
}


// Grounded Search
export const runGroundedSearch = async (prompt: string) => {
    if (!apiKey) throw new Error("API Key not configured");
    const response = await ai.models.generateContent({
       model: flash,
       contents: prompt,
       config: {
         tools: [{googleSearch: {}}],
       },
    });
    
    const text = response.text;
    const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks;
    
    let sources = '';
    if (groundingChunks) {
        const uniqueUris = new Set<string>();
        groundingChunks.forEach(chunk => {
            if (chunk.web?.uri) {
                uniqueUris.add(chunk.web.uri);
            }
        });
        if (uniqueUris.size > 0) {
            sources = '\n\n**Sources:**\n' + Array.from(uniqueUris).map((uri, i) => `${i + 1}. [${uri}](${uri})`).join('\n');
        }
    }
    
    return text + sources;
}
